const express = require('express');
const { VERSION } = require('../config');
const router = express.Router();

const API_CATEGORIES = [
  {
    category: '1. 认证与系统 (Auth & System)',
    endpoints: [
      {
        method: 'GET',
        path: '/api/health',
        auth: '公开',
        summary: '服务健康检查',
        desc: '检查服务运行状态与服务标识。',
        headers: {},
        params: {},
        body: null,
        response: { ok: true, name: 'nimbus-server' },
      },
      {
        method: 'GET',
        path: '/api/auth/status',
        auth: '公开',
        summary: '初始化状态检查',
        desc: '检查当前系统是否已注册初始超级管理员。',
        headers: {},
        params: {},
        body: null,
        response: { initialized: true },
      },
      {
        method: 'POST',
        path: '/api/auth/login',
        auth: '公开',
        summary: '用户登录',
        desc: '使用用户名和密码进行身份验证，获取用于后续接口调用的 JWT Token。',
        headers: { 'Content-Type': 'application/json' },
        params: {},
        body: { username: 'admin', password: 'your_password' },
        response: {
          token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
          user: { id: 'usr_admin', username: 'admin', role: 'admin' },
        },
      },
    ],
  },
  {
    category: '2. 笔记库管理 (Vaults & Permissions)',
    endpoints: [
      {
        method: 'GET',
        path: '/api/vaults',
        auth: 'Bearer Token',
        summary: '获取当前用户可用笔记库列表',
        desc: '返回当前登录用户拥有或被授权协作的所有 Obsidian 笔记库。',
        headers: { Authorization: 'Bearer <token>' },
        params: {},
        body: null,
        response: [
          {
            id: 'vlt_01',
            name: '我的知识库',
            ownerId: 'usr_admin',
            isOwner: true,
            myPermission: 'read-write',
            createdAt: 1720000000000,
          },
        ],
      },
      {
        method: 'POST',
        path: '/api/vaults',
        auth: 'Bearer Token',
        summary: '创建新笔记库',
        desc: '创建一个新的 Obsidian 笔记库空间。',
        headers: { Authorization: 'Bearer <token>', 'Content-Type': 'application/json' },
        params: {},
        body: { name: 'WorkNotes' },
        response: {
          id: 'vlt_02',
          name: 'WorkNotes',
          ownerId: 'usr_admin',
          createdAt: 1720000000000,
        },
      },
      {
        method: 'GET',
        path: '/api/vaults/:vaultId/manifest',
        auth: 'Bearer Token',
        summary: '获取笔记库文件清单',
        desc: '返回库内所有文件的全量相对路径、文件大小、创建/修改时间戳与 SHA-256 哈希值。',
        headers: { Authorization: 'Bearer <token>' },
        params: { vaultId: '笔记库ID' },
        body: null,
        response: {
          'Projects/Roadmap.md': { size: 1024, mtime: 1720000000000, ctime: 1720000000000, hash: 'a1b2c3d4...' },
        },
      },
      {
        method: 'GET',
        path: '/api/vaults/search?q=关键词',
        auth: 'Bearer Token',
        summary: '跨库全文检索',
        desc: '在当前用户所有有权限的笔记库中搜索文件名及笔记内容。',
        headers: { Authorization: 'Bearer <token>' },
        params: { q: '搜索词' },
        body: null,
        response: {
          matches: [
            { vaultId: 'vlt_01', path: 'Notes/Idea.md', snippet: '…核心架构规划…' },
          ],
        },
      },
    ],
  },
  {
    category: '3. 笔记与文件读写 (Files & Storage)',
    endpoints: [
      {
        method: 'GET',
        path: '/api/vaults/:vaultId/files/*',
        auth: 'Bearer Token',
        summary: '读取笔记/文件内容',
        desc: '获取指定相对路径笔记（Markdown、HTML）或附件的二进制/文本内容。',
        headers: { Authorization: 'Bearer <token>' },
        params: { vaultId: '笔记库ID', '*': '文件在库内的相对路径，如 Daily/2026-08-29.md' },
        body: null,
        response: '# 今日日记\n\n- [09:00] 团队晨会',
      },
      {
        method: 'PUT',
        path: '/api/vaults/:vaultId/files/*',
        auth: 'Bearer Token',
        summary: '写入/创建/更新文件',
        desc: '上传或修改笔记内容。支持 X-Mtime 时间戳与 X-Base-Hash 防冲突乐观锁。保存后自动记录历史版本并广播 WebSocket 实时同步。',
        headers: {
          Authorization: 'Bearer <token>',
          'Content-Type': 'text/markdown; charset=utf-8',
          'X-Mtime': '1720000000000',
          'X-Base-Hash': '可选，上一次读取的哈希',
        },
        params: { vaultId: '笔记库ID', '*': '文件相对路径' },
        body: '# Markdown 文本或文件二进制内容',
        response: {
          written: true,
          currentHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
          mtime: 1720000000000,
        },
      },
      {
        method: 'DELETE',
        path: '/api/vaults/:vaultId/files/*',
        auth: 'Bearer Token',
        summary: '删除文件',
        desc: '安全删除笔记或附件（自动放入回收站保护并实时广播删除操作）。',
        headers: { Authorization: 'Bearer <token>' },
        params: { vaultId: '笔记库ID', '*': '文件相对路径' },
        body: null,
        response: { ok: true, deleted: 'Notes/Old.md' },
      },
    ],
  },
  {
    category: '4. 版本历史与回收站 (History & Trash)',
    endpoints: [
      {
        method: 'GET',
        path: '/api/vaults/:vaultId/history?path=...',
        auth: 'Bearer Token',
        summary: '查询笔记历史快照版本',
        desc: '获取指定笔记的所有历史备份快照列表。',
        headers: { Authorization: 'Bearer <token>' },
        params: { vaultId: '笔记库ID', path: '笔记路径' },
        body: null,
        response: [
          { id: 'ver_01', path: 'Projects/Roadmap.md', size: 1024, savedAt: 1720000000000 },
        ],
      },
      {
        method: 'POST',
        path: '/api/vaults/:vaultId/history/:versionId/restore',
        auth: 'Bearer Token',
        summary: '回滚还原历史版本',
        desc: '将指定历史快照内容覆盖回当前笔记，并推送到 Obsidian 客户端。',
        headers: { Authorization: 'Bearer <token>' },
        params: { vaultId: '笔记库ID', versionId: '历史版本ID' },
        body: null,
        response: { ok: true, restoredPath: 'Projects/Roadmap.md' },
      },
      {
        method: 'GET',
        path: '/api/vaults/:vaultId/trash',
        auth: 'Bearer Token',
        summary: '获取回收站文件列表',
        desc: '查询库内所有被删除的文件回收快照。',
        headers: { Authorization: 'Bearer <token>' },
        params: { vaultId: '笔记库ID' },
        body: null,
        response: [
          { id: 'tsh_01', originalPath: 'Draft.md', deletedAt: 1720000000000, size: 520 },
        ],
      },
      {
        method: 'POST',
        path: '/api/vaults/:vaultId/trash/:trashId/restore',
        auth: 'Bearer Token',
        summary: '从回收站恢复文件',
        desc: '将回收站中的文件还原至原目录。',
        headers: { Authorization: 'Bearer <token>' },
        params: { vaultId: '笔记库ID', trashId: '回收记录ID' },
        body: null,
        response: { ok: true, path: 'Draft.md' },
      },
    ],
  },
  {
    category: '5. 冲突与备份 (Conflicts & Backups)',
    endpoints: [
      {
        method: 'GET',
        path: '/api/vaults/:vaultId/conflicts',
        auth: 'Bearer Token',
        summary: '获取并发冲突文件列表',
        desc: '获取多设备或 AI 同时修改产生的冲突文件列表。',
        headers: { Authorization: 'Bearer <token>' },
        params: { vaultId: '笔记库ID' },
        body: null,
        response: [
          { conflictPath: 'Notes/Idea.sync-conflict-20260829.md', basePath: 'Notes/Idea.md' },
        ],
      },
      {
        method: 'POST',
        path: '/api/vaults/:vaultId/conflicts/resolve',
        auth: 'Bearer Token',
        summary: '解决冲突',
        desc: '提交冲突解决策略（保留原版、保留冲突版或提交合并后的新内容）。',
        headers: { Authorization: 'Bearer <token>', 'Content-Type': 'application/json' },
        params: { vaultId: '笔记库ID' },
        body: { conflictPath: 'Notes/Idea.sync-conflict-....md', action: 'keep-conflict | keep-base | custom', content: '...' },
        response: { ok: true },
      },
      {
        method: 'POST',
        path: '/api/vaults/:vaultId/backups',
        auth: 'Bearer Token',
        summary: '创建全库快照备份',
        desc: '立即对当前笔记库生成一个打包好的 ZIP 完整快照。',
        headers: { Authorization: 'Bearer <token>', 'Content-Type': 'application/json' },
        params: { vaultId: '笔记库ID' },
        body: { label: '升级前备份' },
        response: { id: 'bk_123', label: '升级前备份', createdAt: 1720000000000, size: 2048576 },
      },
      {
        method: 'GET',
        path: '/api/vaults/:vaultId/export',
        auth: 'Bearer Token',
        summary: '实时打包导出 ZIP',
        desc: '将整库全部笔记与附件打包为标准 ZIP 文件流下载。',
        headers: { Authorization: 'Bearer <token>' },
        params: { vaultId: '笔记库ID' },
        body: null,
        response: 'Binary ZIP File Stream',
      },
    ],
  },
  {
    category: '6. 外链分享 (Public Shares)',
    endpoints: [
      {
        method: 'GET',
        path: '/api/vaults/:vaultId/shares',
        auth: 'Bearer Token',
        summary: '获取外链分享列表',
        desc: '查看库内所有已创建的公开分享页面。',
        headers: { Authorization: 'Bearer <token>' },
        params: { vaultId: '笔记库ID' },
        body: null,
        response: [
          { id: 'shr_01', filePath: 'Articles/Blog.md', title: '我的博客文章', views: 42, expiresAt: null },
        ],
      },
      {
        method: 'POST',
        path: '/api/vaults/:vaultId/shares',
        auth: 'Bearer Token',
        summary: '创建公开分享外链',
        desc: '为笔记生成 Web 阅读分享链接，支持密码保护、有效期及复制权限控制。',
        headers: { Authorization: 'Bearer <token>', 'Content-Type': 'application/json' },
        params: { vaultId: '笔记库ID' },
        body: { filePath: 'Articles/Blog.md', title: '自定义标题', password: '可选访问密码', expiresDays: 7, allowCopy: true },
        response: { id: 'shr_01', shareUrl: '/share/shr_01' },
      },
      {
        method: 'GET',
        path: '/api/public/shares/:shareId',
        auth: '公开',
        summary: '获取分享文章正文',
        desc: '读者端请求分享文章的 Markdown 正文与元数据。',
        headers: { 'X-Share-Password': '可选密码' },
        params: { shareId: '分享ID' },
        body: null,
        response: { title: '文章标题', content: '# 正文...', allowCopy: true, views: 43 },
      },
    ],
  },
  {
    category: '7. AI / MCP 协议与自省 (Model Context Protocol)',
    endpoints: [
      {
        method: 'GET',
        path: '/api/mcp/tools',
        auth: 'Bearer Token',
        summary: '自省 MCP 工具清单与参数定义',
        desc: '返回当前系统全部 20 个 MCP 工具的元数据、功能描述、分类与参数规则。',
        headers: { Authorization: 'Bearer <token>' },
        params: {},
        body: null,
        response: {
          name: 'nimbus-fast-note-sync',
          version: VERSION,
          toolsCount: 20,
          tools: [{ name: 'read_note', category: '读取与写入', description: '...' }],
        },
      },
      {
        method: 'POST',
        path: '/api/mcp',
        auth: 'Bearer Token',
        summary: 'MCP Streamable HTTP JSON-RPC 端点',
        desc: '接收 Cursor、Cherry Studio、Claude Desktop、Cline 的标准 JSON-RPC 2.0 请求并执行工具调用。',
        headers: {
          Authorization: 'Bearer <token>',
          'Content-Type': 'application/json',
          'X-Default-Vault-Name': '可选默认库名',
        },
        params: {},
        body: {
          jsonrpc: '2.0',
          id: 1,
          method: 'tools/call',
          params: { name: 'list_notes', arguments: { folder: 'Daily' } },
        },
        response: { jsonrpc: '2.0', id: 1, result: { content: [{ type: 'text', text: '...' }] } },
      },
    ],
  },
  {
    category: '8. Git 自动化备份与远端推送 (Git Automation & Sync)',
    endpoints: [
      {
        method: 'GET',
        path: '/api/vaults/:vaultId/git/status',
        auth: 'Bearer Token',
        summary: '获取当前笔记库的 Git 状态',
        desc: '自省当前 Git 仓库初始化状态、分支、未提交文件数、未推送提交、最近提交快照及远端仓库地址。',
        headers: { Authorization: 'Bearer <token>' },
        params: { vaultId: '笔记库ID' },
        body: null,
        response: {
          initialized: true,
          branch: 'main',
          remoteUrl: 'https://github.com/user/notes.git',
          uncommittedCount: 2,
          unpushedCommits: 1,
          lastCommit: { hash: 'a1b2c3d...', author: 'Nimbus Sync', message: 'Auto sync', relativeTime: '5 minutes ago' },
        },
      },
      {
        method: 'POST',
        path: '/api/vaults/:vaultId/git/commit-push',
        auth: 'Bearer Token',
        summary: '立即提交并推送到远端 Git 仓库',
        desc: '将当前笔记库所有修改暂存并提交，推送到配置的 GitHub / Gitee / GitLab 仓库。',
        headers: { Authorization: 'Bearer <token>', 'Content-Type': 'application/json' },
        params: { vaultId: '笔记库ID' },
        body: { message: '手动备份提交' },
        response: { ok: true, committed: true, pushed: true, commitHash: 'd4e5f6...', message: '已成功提交并推送到远端 main 分支' },
      },
      {
        method: 'POST',
        path: '/api/vaults/:vaultId/git/pull',
        auth: 'Bearer Token',
        summary: '从远端 Git 仓库拉取最新更新',
        desc: '从远端 Git 仓库拉取最新变更并自动与本地笔记合并。',
        headers: { Authorization: 'Bearer <token>' },
        params: { vaultId: '笔记库ID' },
        body: null,
        response: { ok: true, message: '拉取成功：Already up to date.' },
      },
      {
        method: 'POST',
        path: '/api/vaults/:vaultId/git/test',
        auth: 'Bearer Token',
        summary: '测试远端 Git 仓库连通性',
        desc: '验证远端 Git 仓库 URL、分支与认证 Token/密码是否正确可访问。',
        headers: { Authorization: 'Bearer <token>', 'Content-Type': 'application/json' },
        params: { vaultId: '笔记库ID' },
        body: { remoteUrl: 'https://github.com/user/notes.git', token: 'ghp_...' },
        response: { ok: true, message: '连通性测试成功！' },
      },
      {
        method: 'GET',
        path: '/api/vaults/:vaultId/git/logs',
        auth: 'Bearer Token',
        summary: '获取最近 Git 提交历史记录',
        desc: '返回笔记库最近的 Git 提交历史（Commit Hash、提交者、时间与提交说明）。',
        headers: { Authorization: 'Bearer <token>' },
        params: { vaultId: '笔记库ID' },
        body: null,
        response: {
          logs: [
            { hash: 'a1b2c3d...', shortHash: 'a1b2c3d', author: 'Nimbus Sync', message: 'Auto sync: 3 files changed', relativeTime: '2 hours ago' },
          ],
        },
      },
    ],
  },
  {
    category: '9. Obsidian 同步插件与 BRAT 规范 (Obsidian Plugin & BRAT)',
    endpoints: [
      {
        method: 'GET',
        path: '/api/settings',
        auth: 'Bearer Token',
        summary: '获取系统全局配置与同步参数',
        desc: '获取服务端的冲突策略、分块传输大小、心跳频率、忽略黑名单等插件运行参数。',
        headers: { Authorization: 'Bearer <token>' },
        params: {},
        body: null,
        response: {
          conflictStrategy: 'conflict_copy',
          chunkSizeMb: 5,
          maxFileSizeMb: 100,
          wsHeartbeatInterval: 30,
          defaultIgnorePatterns: ['.git/**', '.obsidian/cache/**', '.trash/**'],
        },
      },
      {
        method: 'GET',
        path: '/ws',
        auth: 'Token in Query/Auth',
        summary: 'Obsidian WebSocket 实时全双工增量同步长连接',
        desc: 'Obsidian 客户端通过 BRAT 或手动安装 Nimbus Sync 插件后，与 /ws 建立持久双向管道，实现毫秒级变更推送、心跳保活与协同。',
        headers: {},
        params: {
          vaultId: '目标 Vault ID',
          token: '用户主 Token 或专属设备 Token',
          deviceId: '客户端设备标识 (例如 MacBook-Pro)',
        },
        body: null,
        response: {
          type: 'connected',
          vaultId: 'vlt_01',
          serverTime: 1720000000000,
          message: 'WebSocket sync pipeline established',
        },
      },
    ],
  },
];

// Return full documentation schema
router.get('/spec', (req, res) => {
  res.json({
    title: 'Nimbus Fast Note Sync REST API Documentation',
    version: VERSION,
    description: '标准 RESTful API 接口规范与开发文档，覆盖认证、笔记库、文件实时增量读写、版本快照、冲突解决、外链分享及 MCP 协议。',
    categories: API_CATEGORIES,
  });
});

module.exports = router;
